name: Deploy Angular to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to deploy'
        required: true
        default: 'main'
      actor:
        description: 'Actor to deploy'
        required: true
        default: 'github-actions[bot]'
  

jobs:
  build:
    runs-on: ubuntu-latest  

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies & Build Angular project
        working-directory: StreamSphere
        run: |
          npm i && npm ci
          npm install -g @angular/cli
          npm run build -- --output-path .build --base-href /StreamSphere/

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          folder: .build/browser
